[project]
name = "rll"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "torch>=2.8.0",
]
